dev:
  log_retention_in_days: 1
  tracing:
    apiGateway: false
    lambda: false
hmg:
  log_retention_in_days: 1
  tracing:
    apiGateway: false
    lambda: false
prod:
  log_retention_in_days: 15
  tracing:
    apiGateway: true
    lambda: true
